// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jicticrlqffooyrhhzao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppY3RpY3JscWZmb295cmhoemFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTE4NDIsImV4cCI6MjA2NTM2Nzg0Mn0.FMTlWqkcfphYhDUFMi-kuczj3n0YCZmZXPPTgZUqlpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);